version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: flaskuser
      DB_PASSWORD: flaskpass
      DB_NAME: school
    depends_on:
      - mysql
    volumes:
      - .:/app

volumes:
  mysql_data:
